--- #YAML:1.0
name:               POEx-DirNotify
version:            0.00_01
abstract:           dnotify interface for POE
author:
    - Philip Gwyn <gwyn -at- cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    POE:  1.284
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.52
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
